[target.i686-pc-windows-msvc]
linker = "dist\\link_wrapper.exe"
rustflags = [
    "-C", "link-args=oldnames.lib 3rdparty\\YY_Thunks_for_Win2K.obj",
    "-C", "strip=debuginfo",
]

[build]
target = "i686-pc-windows-msvc"
